### ISSUE TITLE
setup_db not working

### ISSUE THREAD

**Issue by ydrea** [archesproject/arches-docs#307] opened 2023-02-08 11:14 UTC
#### describe the issue

trying to install arches on an Ubuntu 22.04

##### please add links to existing docs or code (if relevant)
rop and recreate the database...

SELECT pg_terminate_backend(pid) FROM pg_stat_activity
    WHERE datname IN ('mapulje', 'template_postgis');

DROP DATABASE IF EXISTS mapulje;

CREATE DATABASE mapulje
    WITH OWNER = postgres
        ENCODING = 'UTF8'
        CONNECTION LIMIT=-1
        TEMPLATE = template_postgis;

/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py:395: SecurityWarning: Connecting to 'https://localhost:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(
deleting index : mapulje_terms
Traceback (most recent call last):
  File "/home/ydrea/mapulje/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/management/commands/setup_db.py", line 52, in handle
    self.setup_db()
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/management/commands/setup_db.py", line 190, in setup_db
    management.call_command("es", operation="delete_indexes")
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/management/commands/es.py", line 158, in handle
    self.delete_indexes(name=options["name"])
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/management/commands/es.py", line 277, in delete_indexes
    delete_terms_index()
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/app/search/mappings.py", line 97, in delete_terms_index
    se.delete_index(index=TERMS_INDEX)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/app/search/search.py", line 116, in delete_index
    return self.es.indices.delete(ignore=[400, 404], **kwargs)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/indices.py", line 690, in delete
    return self.perform_request(  # type: ignore[return-value]
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 390, in perform_request
    return self._client.perform_request(
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x7f241da97880>: Failed to establish a new connection: [Errno 111] Connection refused))

**Comment by mradamcox** [comment] 2023-02-08 16:23
Hi @ydrea, it looks like Elasticsearch is not accessible to Arches (this is the cause for the "Connection refused" message). Can you confirm you have ES installed and running, and then try this command again?

**Comment by ekansa** [comment] 2023-02-08 18:04
Hi @ydrea ! 

Yes, I think it's s great idea to update the documentation to be clear that `setup_db` has dependencies on Elasticsearch. I've also run into problems without first starting up the task queue workers via celery. This also needs to be documented.

**Comment by ydrea** [comment] 2023-02-08 20:18
the problem was in installing the database. had to do it manually, but still it doesn't work:

Are you sure you want to destroy and rebuild your database? [y/N] y
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

Error connecting to db with these settings: dbname=mape user=postgres host=localhost port=5432

Have you created the database yet? The quickest way to do so is to supply Postgres superuser credentials in the PG_SUPERUSER and PG_SUPERUSER_PW settings, and then re-run this same command.

**Comment by mradamcox** [comment] 2023-02-08 22:18
Have you tried added the `PG_SUPERUSER` and `PG_SUPERUSER_PW` settings as indicated in the error message? They should be placed in your `settings_local.py` file.

**Comment by ydrea** [comment] 2023-02-09 09:17
umm, these are the contents of my settings_local.py

```
try:
    from .mape.settings import *
except ImportError:
    pass
```
where should I put those?

**Comment by ydrea** [comment] 2023-02-09 16:10
> Hi @ydrea, it looks like Elasticsearch is not accessible to Arches (this is the cause for the "Connection refused" message). Can you confirm you have ES installed and running, and then try this command again?

(ARC) root@ydrea-ThinkPad-L540:/home/ydrea/mapulje# apt install elasticsearch
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
elasticsearch is already the newest version (8.6.1).
0 upgraded, 0 newly installed, 0 to remove and 32 not upgraded.

db_username issue resolved, but the problem persists:

Are you sure you want to destroy and rebuild your database? [y/N] y
Drop and recreate the database...

SELECT pg_terminate_backend(pid) FROM pg_stat_activity
    WHERE datname IN ('mapulje', 'template_postgis');

DROP DATABASE IF EXISTS mapulje;

CREATE DATABASE mapulje
    WITH OWNER = postgres
        ENCODING = 'UTF8'
        CONNECTION LIMIT=-1
        TEMPLATE = template_postgis;

/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py:395: SecurityWarning: Connecting to 'https://localhost:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(
deleting index : mapulje_terms
Traceback (most recent call last):
  File "/home/ydrea/mapulje/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/management/commands/setup_db.py", line 52, in handle
    self.setup_db()
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/management/commands/setup_db.py", line 190, in setup_db
    management.call_command("es", operation="delete_indexes")
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/management/commands/es.py", line 158, in handle
    self.delete_indexes(name=options["name"])
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/management/commands/es.py", line 277, in delete_indexes
    delete_terms_index()
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/app/search/mappings.py", line 97, in delete_terms_index
    se.delete_index(index=TERMS_INDEX)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/arches/app/search/search.py", line 116, in delete_index
    return self.es.indices.delete(ignore=[400, 404], **kwargs)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/indices.py", line 690, in delete
    return self.perform_request(  # type: ignore[return-value]
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 390, in perform_request
    return self._client.perform_request(
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/ydrea/ARC/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x7f27b88878b0>: Failed to establish a new connection: [Errno 111] Connection refused))

**Comment by ekansa** [comment] 2023-02-09 18:14
@ydrea yep! I've been through similar frustrations trying to get Arches up and running.  I'm trying to figure out a good approach to providing step by step guidance, since there are many, many, many things to configure and diagnosing a problem is not always straightforward.

A few things to check. I see you installed Elasticsearch.  Can you check to see if it is actually up and running? 

One way to check is to send a request to Elasticsearch. Assuming it is on your localhost s and using the default port (9200), in your terminal try something like:

`curl http://localhost:9200/_cluster/health`

You should get a response with some JSON and that will tell you that Elasticsearch is running.

**Comment by ekansa** [comment] 2023-02-10 00:02
PS if you're having trouble seeing Elasticsearch working, Step 2 in this guide maybe helpful: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-22-04

**Comment by ekansa** [comment] 2023-05-15 21:23
I'm going to close this issue. If we need to make updates to the documentation about Elasticsearch connections, we can file a new ticket.

**Closed by ekansa** 2023-05-15 21:23 UTC
