### ISSUE TITLE
Document plugin development

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-docs#172] opened 2020-01-02 23:05 UTC
Documentation for plugins needs to be added to the following page: https://arches.readthedocs.io/en/latest/functions-widgets-datatypes/https://arches.readthedocs.io/en/latest/functions-widgets-datatypes/

**Comment by mradamcox** [comment] 2020-10-22 01:42
duplicate of https://github.com/archesproject/arches-docs/issues/129, closing.

**Closed by mradamcox** 2020-10-22 01:42 UTC
